spring:
  datasource: 
#    url: 'jdbc:mysql://dev-aurora-mysql.cvytkk0k4stw.ap-northeast-2.rds.amazonaws.com:3306/nutella-event'
#    username: 'nutella-event'
#    password: 'sNteLlfk2$%Tsw!1'
    hikari: 
      jdbc-url: jdbc:h2:mem:test
      username: sa
      password: #1234
      driver-class-name: org.h2.Driver
#    driverClassName: org.h2.Driver
#    url: 'jdbc:h2:~/test;AUTO_SERVER=TRUE'
#    username: sa
#    password: 1234
    tomcat: 
      max-active: 4
      max-idle: 4
  jpa: 
    database: H2
    hibernate.ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
#    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    
    
#  session:
#    store-type: jdbc
#    jdbc:
#      initialize-schema: always
#      schema: classpath:org/springframework/session/jdbc/schema-mysql.sql

  thymeleaf:
    mode: LEGACYHTML5

  devtools:
    livereload:
      enabled: true
      
  h2:
    console:
      enabled: true
 
server: 
  error:
    whitelabel:
      enabled: false
      
  tomcat:
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for
    
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    kr.co.nutellaevent: DEBUG
  
---
spring:
  profiles: development
  datasource:
    tomcat:
      max-active: 2
      max-idle: 2
  
logging:
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR
    kr.co.nutellaevent: DEBUG
      
---
spring:
  profiles: production
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    tomcat:
      max-active: 10
      max-idle: 10  
  
logging:
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR
    kr.co.nutellaevent: ERROR